---
# tasks file for mariadb
- name: install mariadb package
  yum: name={{item}} state=installed
  with_items:
  - mariadb-server
  - MySQL-python
  - firewalld

- name: configure selinux to start mysql on any port
  seboolean: name=mysql_connect_any state=true persistent=yes

- name: create mariadb configuration file
  template: src=my.cnf.j2 dest=/etc/my.cnf
  notify: restart mariadb

- name: create maridb log file
  file: path=/var/log/mysqld.log state=touch owner=mysql group=mysql

- name: create maridb PID directory
  file: path=/var/log/mysqld state=directory owner=mysql group=mysql

- name: Start mariadb service
  service: name=mariadb state=started enabled=yes

- name: Start firewalld
  service: name=firewalld state=started

- name: insert firewalld rule
  firewalld: port={{mysql_port}}/tcp permanent=true state=enabled

- name: create application database
  mysql_db: name={{dbname}} state=present

- name: create application database user
  mysql_user: name={{dbuser}} password={{upassword}} priv=*.*:A
