---
- hosts: all
  tasks:
  - name: Install prerequisites
    become: yes
    apt: 
      name: ['apt-transport-https']
      state: present
      update_cache: yes

  - name: Add Sublime Text GPG key
    become: yes
    apt_key: url=https://download.sublimetext.com/sublimehq-pub.gpg

  - name: Add Sublime Text APT repository
    become: yes
    apt_repository:
      repo: deb https://download.sublimetext.com/ apt/stable/

  - name: Install Sublime Text
    become: yes
    apt:
      name: ['sublime-text']
      state: present
      update_cache: yes
