---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: "/drupal-data"

# ssh node01 ; sudo mkdir /drupal-data
# kubectl get pv ; kubectl create -f pv.yaml
