---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: drupal-mysql-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 5Gi
  hostPath:
    path: "/drupal-mysql-data"

# ssh node01 ; sudo mkdir /drupal-mysql-data

# kubectl get pv ; kubectl create -f pv.yaml
