---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: drupal
  name: drupal
spec:
  replicas: 1
  selector:
    matchLabels:
      app: drupal
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: drupal
    spec:
      initContainers:
      - name: init-sites-volume
        command: [ "/bin/bash", "-c"]
        args: [ 'cp -r /var/www/html/sites/ /data/; chown www-data:www-data /data/ -R' ]
        image: drupal:8.6
        volumeMounts:
        - mountPath: "/data"
          name: pvc
      containers:
      - image: drupal:8.6
        name: drupal
        resources: {}
        volumeMounts:
        - mountPath: "/var/www/html/modules"
          name: pvc
          subPath: modules
        - mountPath: "/var/www/html/sites"
          name: pvc
          subPath: sites
        - mountPath: "/var/www/html/profiles"
          name: pvc
          subPath: profiles
        - mountPath: "/var/www/html/themes"
          name: pvc
          subPath: themes
      volumes:
      - name: pvc
        persistentVolumeClaim:
          claimName: drupal-pvc
      - name: workdir
        emptyDir: {}
status: {}

---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: drupal-service
  name: drupal-service
spec:
  ports:
  - name: "30095"
    nodePort: 30095
    protocol: TCP
    port: 3095
  selector:
    app: drupal
  type: NodePort
status:
  loadBalancer: {}

# kubectl create -f drupal.yaml ; watch -n 1 kubectl get pods ; kubectl get svc drupal-service


# Solution:  Nyk skan jiva schedulara! Zer poda! Zer poda! Zer poda! 