name: Master Branch

on:
  push:
    branches:
      - "master"

jobs:
  test:
    name: Run Unit Test
    runs-on: ubuntu-latest


    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Maven Package
        run: cd cicd/github_actions/maven_helm_k8s ; mvn -B clean package -DskipTests

      - name: Maven Verify
        run: cd cicd/github_actions/maven_helm_k8s ; mvn -B clean verify

  docker:
    name: Publish to Docker Hub
    runs-on: ubuntu-latest
    needs: [test]
    env:
      REPO: ${{ secrets.DOCKER_REPO}}

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USER }}/$REPO:latest .

      - name: Publish Docker image
        run: docker push ${{ secrets.DOCKER_USER }}//$REPO:latest

  deploy:
    name: Deploy to K8s
    runs-on: ubuntu-latest
    needs: [docker]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up Google Cloud
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          project_id: $${{ secrets.GCP_PROJECT_ID}}
          service_account_key: $${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true
      - run: gcloud info

      - name: Generate kube config file
        run: gcloud container clusters get-credentials sample_cluster --zone=${{ secrets.CLUSTER_ZONE }}

      - name: Setup Helm 3
        run: |-
          curl -fsSL -o get_helm.sh https://raw.githubusercontent.com/helm/helm/master/scripts/get-helm-3
          chmod 700 get_helm.sh
          ./get_helm.sh

      - name: Deploy
        run: helm upgrade -i -f ./deployment/helm/values.yaml github-actions-test ./deployment/helm/
